import { useApp } from '../../context/AppContext';
import { useChatInput } from '../../hooks/useChatInput';
import { TokenStatsBar } from './TokenStatsBar';
import { SendButton } from './SendButton';
import { calculateMaxTokens } from '../../helpers/calculate-max-tokens';
import { ProviderDropdown } from './ProviderDropdown';
import { ModelDropdown } from './ModelDropdown';
import type { Provider } from '../../types/types';
import type { TokenStats } from '../../hooks/useChat';

interface Props {
  onSend: (content: string, provider: Provider, model: string, conversationId?: string) => void;
  tokenStats: TokenStats | null;
  isStreaming: boolean;
  onStop: () => void;
}

export default function ChatInput({ onSend, tokenStats, isStreaming, onStop }: Props) {
  const {
    activeConversationId,
    activeProvider,
    activeModel,
    setActiveModel,
    providers,
    updateConversationTitle,
    setActiveProvider,
    createConversation,
    setActiveConversationId,
  } = useApp();

  const {
    input, setInput,
    showProviderDropdown, setShowProviderDropdown,
    showModelDropdown, setShowModelDropdown,
    displayModelName, handleModelChange, handleProviderSelect,
    handleSubmit, handleKeyDown, availableModels,
  } = useChatInput({
    onSend,
    activeConversationId,
    activeProvider,
    activeModel,
    setActiveModel,
    setActiveProvider,
    updateConversationTitle,
    createConversation,
    setActiveConversationId,
  });

  const maxTokens = calculateMaxTokens(availableModels, displayModelName(), activeProvider?.model_info ?? null);

  if (!activeProvider) {
    return (
      <div className="border-t theme-border px-4 py-3">
        <div className="max-w-chat-input-max mx-auto text-center">
          <p className="text-xs text-gray-500">
            No provider configured. Go to Settings to add one.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="theme-main">
      <div className="max-w-3xl mx-auto px-4 py-3">
        <TokenStatsBar tokenStats={tokenStats} maxTokens={maxTokens} />

        <div className="chat-input-container flex flex-col border theme-border-light rounded-2xl">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Message..."
            rows={1}
            className="chat-input bg-transparent text-sm px-4 pt-3 pb-2 focus:outline-none resize-none placeholder-gray-500"
          />
          <div className="flex items-center justify-between px-3 pb-2 pt-1">
            <div className="flex items-center gap-3 min-w-0">
              <ProviderDropdown
                providers={providers}
                activeProvider={activeProvider}
                showProviderDropdown={showProviderDropdown}
                onToggle={() => {
                  setShowProviderDropdown(!showProviderDropdown);
                  setShowModelDropdown(false);
                }}
                onSelect={handleProviderSelect}
              />

              {availableModels.length > 1 && (
                <ModelDropdown
                  availableModels={availableModels}
                  displayModelName={displayModelName()}
                  showModelDropdown={showModelDropdown}
                  onToggle={() => {
                    setShowModelDropdown(!showModelDropdown);
                    setShowProviderDropdown(false);
                  }}
                  onSelect={handleModelChange}
                />
              )}
            </div>

            <SendButton
              isStreaming={isStreaming}
              hasInput={input.trim().length > 0}
              onSend={handleSubmit}
              onStop={onStop}
            />
          </div>
        </div>

        <p className="text-[11px] theme-text-muted text-center mt-2">
          AI responses generated by your configured provider.
        </p>
      </div>
    </div>
  );
}
