import { useState, useRef, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { Send, ChevronDown, ChevronUp } from 'lucide-react';
import type { Provider } from '../types';

interface Props {
  onSend: (content: string, provider: Provider) => void;
}

export default function ChatInput({ onSend }: Props) {
  const { activeConversationId, activeProvider, providers, updateConversationTitle, setActiveProvider } = useApp();
  const [input, setInput] = useState('');
  const [showProviderDropdown, setShowProviderDropdown] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 200) + 'px';
    }
  }, [input]);

  const handleSubmit = async () => {
    if (!input.trim() || !activeConversationId || !activeProvider) return;

    const content = input.trim();
    setInput('');

    // If first message, update conversation title
    const messageCount = await window.chatApi.messages.get(activeConversationId);
    if (messageCount.length === 0) {
      await updateConversationTitle(activeConversationId, content.slice(0, 50));
    }

    onSend(content, activeProvider);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  if (!activeProvider) {
    return (
      <div className="border-t border-border px-4 py-3">
        <div className="max-w-chat-max mx-auto text-center">
          <p className="text-xs text-gray-500">
            No provider configured. Go to Settings to add one.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="border-t border-border bg-main">
      <div className="max-w-chat-max mx-auto px-4 py-3">
        {/* Provider selector */}
        <div className="flex items-center justify-between mb-2">
          <div className="relative">
            <button
              onClick={() => setShowProviderDropdown(!showProviderDropdown)}
              className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-200 transition-colors"
            >
              <span>{activeProvider.name}</span>
              <span className="text-gray-600">•</span>
              <span>{activeProvider.default_model}</span>
              {showProviderDropdown ? (
                <ChevronUp className="w-3 h-3" />
              ) : (
                <ChevronDown className="w-3 h-3" />
              )}
            </button>

            {showProviderDropdown && providers.length > 1 && (
              <div className="absolute bottom-full mb-2 left-0 bg-sidebar border border-border-light rounded-lg shadow-xl py-1 min-w-[200px] z-10">
                {providers.map((p) => (
                  <button
                    key={p.id}
                    className="w-full text-left px-3 py-2 text-xs text-gray-300 hover:bg-sidebar-hover transition-colors"
                    onClick={() => {
                      setActiveProvider(p);
                      setShowProviderDropdown(false);
                    }}
                  >
                    <div className="font-medium">{p.name}</div>
                    <div className="text-gray-500">{p.default_model}</div>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Input area */}
        <div className="relative flex items-end bg-input border border-border-light rounded-2xl focus-within:border-gray-500 transition-colors">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Message..."
            rows={1}
            className="chat-input flex-1 bg-transparent text-gray-100 text-sm px-4 py-3 pr-12 focus:outline-none resize-none placeholder-gray-500"
          />
          <button
            onClick={handleSubmit}
            disabled={!input.trim()}
            className={`absolute right-2 bottom-2 p-2 rounded-full transition-all ${
              input.trim()
                ? 'bg-gray-600 hover:bg-gray-500 text-white'
                : 'bg-transparent text-gray-600 cursor-not-allowed'
            }`}
          >
            <Send className="w-4 h-4" />
          </button>
        </div>

        <p className="text-[10px] text-gray-600 text-center mt-2">
          AI responses generated by your configured provider.
        </p>
      </div>
    </div>
  );
}
